// Skills are ordered the same way as they appear in the game.
export const skills = [
  'attack',
  'strength',
  'defence',
  'ranged',
  'prayer',
  'magic',
  'runecraft',
  'construction',
  'hitpoints',
  'agility',
  'herblore',
  'thieving',
  'crafting',
  'fletching',
  'slayer',
  'hunter',
  'mining',
  'smithing',
  'fishing',
  'cooking',
  'firemaking',
  'woodcutting',
  'farming',
  'sailing',
] as const;

// Combat skills contribute to combat level. Slayer is not included here as it
// does not increase combat level despite revolving entirely around combat.
export const combatSkills = [
  'attack',
  'strength',
  'defence',
  'ranged',
  'prayer',
  'magic',
  'hitpoints',
] as const;

// Non-combat skills do not contribute to combat level but sometimes are still
// used in combat activities (e.g. skilling bosses).
export const nonCombatSkills = [
  'runecraft',
  'construction',
  'agility',
  'herblore',
  'thieving',
  'crafting',
  'fletching',
  'slayer',
  'hunter',
  'mining',
  'smithing',
  'fishing',
  'cooking',
  'firemaking',
  'woodcutting',
  'farming',
  'sailing',
] as const;

export const skillingFilters = [
  'attack',
  'strength',
  'defence',
  'ranged',
  'prayer',
  'magic',
  'runecraft',
  'construction',
  'hitpoints',
  'agility',
  'herblore',
  'thieving',
  'crafting',
  'fletching',
  'slayer',
  'hunter',
  'mining',
  'smithing',
  'fishing',
  'cooking',
  'firemaking',
  'woodcutting',
  'farming',
  'sailing',
] as const;

export const activityCategories = [
  'agility',
  'attack',
  'chest',
  'construction',
  'cooking',
  'crafting',
  'defence',
  'diaries',
  'dungeon',
  'farming',
  'firemaking',
  'fishing',
  'fletching',
  'herblore',
  'hitpoints',
  'hunter',
  'location',
  'magic',
  'melee',
  'mining',
  'misc',
  'music',
  'npc',
  'prayer',
  'pvm',
  'pvp',
  'quest',
  'ranged',
  'runecraft',
  'sailing',
  'skilling',
  'slayer',
  'smithing',
  'spell',
  'spellbook',
  'strength',
  'thieving',
  'woodcutting',
] as const;

export const iconOrder = [
  // combat
  'Raids',
  'Master_Reanimation',
  'Monster_Examine',
  'Combat_icon',
  'Skull_(status)_icon',
  'Hitpoints_icon',
  'Attack_icon',
  'Strength_icon',
  'Defence_icon',
  'Ranged_icon',
  'Prayer_icon',
  'Magic_icon',
  'Standard_spellbook',
  'Ancient_spellbook',
  'Arceuus_spellbook',
  'Lunar_spellbook',
  // skilling
  'Runecraft_icon',
  'Construction_icon',
  'Agility_icon',
  'Herblore_icon',
  'Thieving_icon',
  'Crafting_icon',
  'Fletching_icon',
  'Slayer_icon',
  'Hunter_icon',
  'Mining_icon',
  'Smithing_icon',
  'Fishing_icon',
  'Cooking_icon',
  'Firemaking_icon',
  'Woodcutting_icon',
  'Farming_icon',
  // other
  'Flax',
  'Crystal_key',
  'Minigame_icon',
  'Quest_point_icon',
  'Achievement_Diaries_icon',
  'Distractions_and_Diversions',
  'Music',
  'Stats_icon',
  'Collection_log',
  'Map_link_icon',
  'Dungeon_map_link_icon',
  'Anvil_icon',
  'Furnace_icon',
  'Cooking_range_icon',
];

export const itemIds = {
  bars: [
    'Bronze_bar',
    'Blurite_bar',
    'Lunar_bar',
    'Iron_bar',
    'Elemental_metal',
    'Silver_bar',
    'Steel_bar',
    'Gold_bar',
    'Lovakite_bar',
    'Mithril_bar',
    'Adamantite_bar',
    'Runite_bar',
  ],
  food: [
    'Shrimps',
    'Cooked_chicken',
    'Cooked_meat',
    'Bread',
    'Trout',
    'Salmon',
    'Tuna',
    'Jug_of_wine',
    'Stew',
    'Cake',
    'Lobster',
    'Bass',
    'Plain_pizza',
    'Swordfish',
    'Snowy_knight_mix',
    'Potato_with_cheese',
    'Monkfish',
    'Cooked_karambwan',
    'Blighted_karambwan',
    'Curry',
    'Ugthanki_kebab',
    'Guthix_rest',
    'Shark',
    'Mushroom_potato',
    'Sea_turtle',
    'Cooked_sunlight_antelope',
    'Pineapple_pizza',
    'Wild_pie',
    'Summer_pie',
    'Tuna_potato',
    'Dark_crab',
    'Manta_ray',
    'Blighted_manta_ray',
    'Anglerfish',
    'Blighted_anglerfish',
    'Cooked_dashing_kebbit',
    'Cooked_moonlight_antelope',
    'Saradomin_brew',
  ],
  gems: [
    'Opal',
    'Jade',
    'Red_topaz',
    'Sapphire',
    'Emerald',
    'Ruby',
    'Diamond',
    'Dragonstone',
    'Onyx',
    'Zenyte',
  ],
  hides: [
    'Green_dragonhide',
    'Blue_dragonhide',
    'Red_dragonhide',
    'Black_dragonhide',
    'Wool',
    'Cowhide',
    'Snake_hide',
    'Yak-hide',
  ],
  logs: [
    'Achey_tree_logs',
    'Logs',
    'Oak_logs',
    'Willow_logs',
    'Teak_logs',
    'Juniper_logs',
    'Bark',
    'Maple_logs',
    'Mahogany_logs',
    'Arctic_pine_logs',
    'Yew_logs',
    'Blisterwood_logs',
    'Magic_logs',
    'Redwood_logs',
  ],
  misc: [
    'Plank',
    'Mushroom',
    'Swamp_paste',
    'Flax',
    'Bow_string',
    'Seaweed',
    'Bucket_of_sand',
    'Soda_ash',
    'Clay',
    'Soft_clay',
    'Te_salt',
    'Efh_salt',
    'Urt_salt',
    'Basalt',
    'Saltpetre',
    'Volcanic_sulphur',
    'Granite',
    'Sandstone',
    'Limestone',
    'Limestone_brick',
    'Marble_block',
    'Magic_stone',
    'Gold_leaf',
    'Condensed_gold',
  ],
  ores: [
    'Tin_ore',
    'Copper_ore',
    'Blurite_ore',
    'Iron_ore',
    'Coal',
    'Silver_ore',
    'Gold_ore',
    'Mithril_ore',
    'Lunar_ore',
    'Lovakite_ore',
    'Adamantite_ore',
    'Runite_ore',
    'Daeyalt_ore',
    'Amethyst',
    'Infernal_shale',
  ],
  remains: [
    'Bones',
    'Monkey_bones',
    'Bat_bones',
    'Big_bones',
    'Jogre_bones',
    'Zogre_bones',
    'Shaikahan_bones',
    'Babydragon_bones',
    'Dragon_bones',
    'Lava_dragon_bones',
    'Dagannoth_bones',
    'Superior_dragon_bones',
    'Wyrmling_bones',
    'Wyrm_bones',
    'Wyvern_bones',
    'Drake_bones',
    'Hydra_bones',
    'Sun-kissed_bones',
    'Blessed_bone_shards',
    'Fayrg_bones',
    'Raurg_bones',
    'Ourg_bones',
    'Loar_remains',
    'Phrin_remains',
    'Riyl_remains',
    'Asyn_remains',
    'Fiyr_remains',
    'Urium_remains',
    'Fiendish_ashes',
    'Vile_ashes',
    'Malicious_ashes',
    'Abyssal_ashes',
    'Infernal_ashes',
  ],
  runes: [
    'Air_rune',
    'Mind_rune',
    'Water_rune',
    'Mist_rune',
    'Earth_rune',
    'Dust_rune',
    'Mud_rune',
    'Fire_rune',
    'Smoke_rune',
    'Steam_rune',
    'Body_rune',
    'Lava_rune',
    'Cosmic_rune',
    'Sunfire_rune',
    'Chaos_rune',
    'Astral_rune',
    'Nature_rune',
    'Law_rune',
    'Death_rune',
    'Blood_rune',
    'Soul_rune',
    'Aether_rune',
    'Wrath_rune',
    'Rune_essence',
    'Pure_essence',
    'Dense_essence_block',
    'Dark_essence_block',
    'Daeyalt_essence',
    'Blood_essence',
    'Tainted_essence_chunk',
  ],
  secondaries: [
    'Unicorn_horn',
    'Desert_goat_horn',
    'Gorak_claws',
    'Kebbit_teeth',
    'Nail_beast_nails',
    "Toad's_legs",
    'Araxyte_venom_sack',
    'Cactus_spine',
    'Potato_cactus',
    'Mort_myre_fungus',
    'Yew_roots',
    'Magic_roots',
    'Limpwurt_root',
    'Snape_grass',
    'Bird_nest',
    'Lily_of_the_sands',
    'Nightshade',
    'Jangerberries',
    'Poison_ivy_berries',
    'White_berries',
    "Red_spiders'_eggs",
    'Amylase_crystal',
    'Lava_scale_shard',
    'Lava_scale',
    'Blue_dragon_scale',
    'Eye_of_newt',
    'Garlic',
    'Chocolate_bar',
    'Demonic_tallow',
    'Ashes',
    'Crushed_superior_dragon_bones',
    'Crystal_dust',
    'Nihil_dust',
    'Silver_dust',
    'Volcanic_ash',
    'Wine_of_zamorak',
    'Coconut_milk',
    'Vial_of_blood',
    'Aldarium',
    'Ancient_essence',
    "Zulrah's_scales",
    'Swamp_tar',
  ],
};

export const healing: Record<string, number | string> = {
  ['Anglerfish']: '3-22',
  ['Bass']: 13,
  ['Blighted_anglerfish']: '3-22',
  ['Blighted_karambwan']: 18,
  ['Blighted_manta_ray']: 22,
  ['Bread']: 5,
  ['Cake']: '4x3',
  ['Cooked_chicken']: 3,
  ['Cooked_dashing_kebbit']: '13+10',
  ['Cooked_karambwan']: 18,
  ['Cooked_meat']: 3,
  ['Cooked_moonlight_antelope']: '14+12',
  ['Cooked_sunlight_antelope']: '12+9',
  ['Curry']: 19,
  ['Dark_crab']: 22,
  ['Guthix_rest']: '5x4',
  ['Jug_of_wine']: 11,
  ['Lobster']: 12,
  ['Manta_ray']: 22,
  ['Monkfish']: 16,
  ['Mushroom_potato']: 20,
  ['Pineapple_pizza']: '11x2',
  ['Plain_pizza']: '7x2',
  ['Potato_with_cheese']: 16,
  ['Salmon']: 9,
  ['Saradomin_brew']: '16x4',
  ['Sea_turtle']: 21,
  ['Shark']: 20,
  ['Shrimps']: 3,
  ['Snowy_knight_mix']: '8x2',
  ['Stew']: 11,
  ['Summer_pie']: '11x2',
  ['Swordfish']: 14,
  ['Trout']: 7,
  ['Tuna_potato']: 22,
  ['Tuna']: 10,
  ['Ugthanki_kebab']: 19,
  ['Wild_pie']: '11x2',
};
